### ISSUE TITLE
Is there any way to use this with subdomain masking?

### ISSUE THREAD

**Issue by alexdovzhanyn** [fnando/sinatra-subdomain#18]
I have an aws instance that is using this, my subdomain is essentially subdomain.aws-url.com, and im trying to use mywebsite.com to mask this subdomain. The problem is, it doesn't use my subdomain routes, just my bare, non-subdomain routes

**Comment by fnando** [comment]
So, on your browser you hit mywebsite.com instead of the underlying AWS url? I can't see how to make it work, since what gets to your Sinatra app is the final hostname (mywebsite.com).

You can achieve the result you by using NGINX or any other reverse proxy. I created a simple example showing how to do it at https://gist.github.com/fnando/99b105f5ae6b30818af4658c4e834d8c.

**Comment by alexdovzhanyn** [comment]
Awesome, thanks! I had a feeling this would be the case but I wanted to ask just in case
